### ISSUE TITLE
how to restore all windows when open pycharm again

### ISSUE THREAD

**Issue by username7171** [JetBrains/awesome-pycharm#12]
I usually use 1 pycharm window for one project.

I need to shut down the computer every day.

Is there any way to restore all closed windows when I continue the work the next day?

I am using window10.

**Comment by pauleveritt** [comment]
Hi, this repo isn't really a PyCharm support channel. [This page lists some of the options](https://intellij-support.jetbrains.com/hc/en-us/?pycharm#) (Twitter, issue tracker, email, forum, etc.)
