### ISSUE TITLE
Why can't I rename file in Pycharm?

### ISSUE THREAD

**Issue by chinmayroy** [JetBrains/awesome-pycharm#19]
Please fix this:

I'm using the Pycharm Professional edition. I days ago, I remained file clicked on file then right clicked a mouse 

    >> Refactore >> Rename

Now, I can't rename files using the same way. Is there any other way to rename a file?

**Comment by pauleveritt** [comment]
Hi, this repo isn't really about support questions, it's more just an (old, outdated) attempt to collect links. Want to get a ticket in the support system?

**Comment by chinmayroy** [comment]
@pauleveritt thanks for your reply
