### ISSUE TITLE
"scanning files to index" --- issue

### ISSUE THREAD

**Issue by chinmayroy** [JetBrains/awesome-pycharm#20]
It is taking a long time. Do you know how I can solve this issue?
When I updated my pycharm then I got this issue.

**Comment by pauleveritt** [comment]
As mentioned in your other ticket, this repo isn't for PyCharm support. In fact, it's basically inactive.

**Comment by pauleveritt** [comment]
To answer the question though...when you update PyCharm, it has new indexing machinery, so it triggers a one-time reindexing. You can still do most of your work while indexing is happening.
